image: artifactory.pegadaian.co.id:8084/docker:latest

variables:
  DOCKER_AUTH_CONFIG: '{"auths": {"artifactory.pegadaian.co.id:5443": {"auth": "$DOCKER_AU_CONFIG"},"artifactory.pegadaian.co.id:8084": {"auth": "$DOCKER_AU_CONFIG"}}}'
  REGISTRY: artifactory.pegadaian.co.id:8084

stages:
  - deploy
  - snapshot

deploy:
  image: $REGISTRY/node:20.10.0-alpine
  stage: deploy
  script:
    - apk add --no-cache jq
    - echo "registry=$NPM_REGISTRY_URL" > .npmrc
    - echo "//artifactory.pegadaian.co.id/repository/npm-hosted-01/:_auth=$NPM_AUTH_TOKEN" >> .npmrc
    # -------------------------------------------------------------
    # - echo "Current version :$CURRENT_VERSION"
    # - echo "All available versions :$ALL_VERSIONS"
    # -------------------------------------------------------------
    - CURRENT_VERSION=$(npm view . version)
    - ALL_VERSIONS=$(npm view . versions --json)
    - YOUR_VERSION=$(node -p "require('./package.json').version")
    # -------------------------------------------------------------
    - echo "Your Project Version :$YOUR_VERSION"
    - echo "Latest version :$(echo $ALL_VERSIONS | jq -r '.[-1]')"
    - if [ "$CURRENT_VERSION" = "$YOUR_VERSION" ]; then 
        echo "Version deprecated, rebuilding at $CURRENT_VERSION..."; 
        npm rebuild --userconfig .npmrc; 
      elif [ "$YOUR_VERSION" = "$(echo $ALL_VERSIONS | jq -r '.[-1]')" ]; then 
        echo "New version is the latest, publishing..."; 
        npm publish --userconfig .npmrc; 
      else 
        echo "New version is not the latest, skipping publish."; 
      fi
  only:
    - master

snapshot:
  image: $REGISTRY/node:20.10.0-alpine
  stage: snapshot
  script:
    - echo "registry=$NPM_REGISTRY_URL" > .npmrc
    - echo "//artifactory.pegadaian.co.id/repository/npm-hosted-01/:_auth=$NPM_AUTH_TOKEN" >> .npmrc
    - npm publish --userconfig .npmrc
  only:
    - /^dev-update-component$/
