image: artifactory.pegadaian.co.id:8084/docker:latest

variables:
  DOCKER_AUTH_CONFIG: '{"auths": {"artifactory.pegadaian.co.id:5443": {"auth": "$DOCKER_AU_CONFIG"},"artifactory.pegadaian.co.id:8084": {"auth": "$DOCKER_AU_CONFIG"}}}'
  REGISTRY: artifactory.pegadaian.co.id:8084

stages:
  # - deploy
  - snapshot

# deploy:
#   image: $REGISTRY/node:3-openjdk-17-slim
#   stage: deploy
#   script:
#     - mvn -B source:jar deploy
#   only:
#     - master

snapshot:
  image: $REGISTRY/node:20.10.0-alpine
  stage: snapshot
  script:
    # - npm config set registry https://artifactory.pegadaian.co.id/repository/npm-hosted-01/
    - echo "https://artifactory.pegadaian.co.id/repository/npm-hosted-01/:_authToken=YWd1cy5kaWFuYTphZ3VzMTIzIQ==" > .npmrc
    - cat .npmrc
    - npm publish
  only:
    - /^snapshot-.*$/
