import type { App } from 'vue';
import type { Component } from 'vue';

declare const KitVue: {
  install(app: App): void;
};

export const components: Record<string, Component>;

// Core declarations for all components
export const Accordion: Component;
export const AccordionItem: Component;
export const AddAmount: Component;
export const AddAmountItem: Component;
export const AddAmountDenom: Component;
export const Alert: Component;
export const AlertVarian: Component;
export const Aspect: Component;
export const Breadcrumb: Component;
export const Button: Component;
export const ButtonSize: Component;
export const ButtonRightSlider: Component;
export const ButtonLeftSlider: Component;
export const CardAccount: Component;
export const CardArticle: Component;
export const CardArticleHighlight: Component;
export const CardContent: Component;
export const CardEvent: Component;
export const CardFile: Component;
export const CardProduct: Component;
export const CardProductKonvensional: Component;
export const CardProductSyariah: Component;
export const CardPromo: Component;
export const CardPromoCode: Component;
export const CardVoucher: Component;
export const DatePicker: Component;
export const Dropdown: Component;
export const InputDropdownMultiple: Component;
export const InputDropdownHeader: Component;
export const FilePickerLG: Component;
export const FilePickerSM: Component;
export const InputPersen: Component;
export const Input: Component;
export const InputKtp: Component;
export const TextArea: Component;
export const ModalComponent: Component;
export const InputSmallDate: Component;
export const ListGroupUnordered: Component;
export const ListGroupUnit: Component;
export const ListOrdered: Component;
export const ListSorted: Component;
export const TableData: Component;
export const DataTable: Component;
export const TableSticky: Component;
export const DataApps: Component;
export const Badge: Component;
export const DropdownGroupItem: Component;
export const DropdownItem: Component;
export const InputSearch: Component;
export const InputText: Component;
export const InputNominalStart: Component;
export const InputWithActionButton: Component;
export const CalendarDropdown: Component;
export const InputCamera: Component;
export const DateRangePicker: Component;
export const InputMonth: Component;
export const TimePickerResponsive: Component;
export const TimePicker: Component;
export const InputNIK: Component;
export const InputTimePicker: Component;
export const InputSearchQR: Component;
export const DateRangePickerOption: Component;
export const NewInputCamera: Component;
export const InputPhone: Component;
export const ContentTimePicker: Component;
export const InputDatePicker: Component;
export const SideNavCMS: Component;
export const ItemSideNav: Component;
export const NavbarCorporate: Component;
export const TabPembinaan: Component;
export const BerandaHeader: Component;
export const NavBackNavigator: Component;
export const Tooltip: Component;
export const Radio: Component;
export const StackedBarChart: Component;
export const DoughnutChart: Component;
export const LineChart: Component;
export const BarChart: Component;
export const SideStepper: Component;
export const SideStepperTest: Component;
export const Checkbox: Component;
export const Label: Component;
export const LabelIcon: Component;
export const StepperVarian: Component;
export const Stepper: Component;
export const TabProduct: Component;
export const TabGroup: Component;
export const TabKategori: Component;
export const ImageView: Component;
export const AutoComplete: Component;
export const TablePagination: Component;
export const CustomTable: Component;
export const BottomSheet: Component;
export const Switch: Component;
export const FilterCMS: Component;
export const InputFilter: Component;
export const ModalLoad: Component;
export const ModalSlider: Component;
export const CustomModal: Component;
export const HeaderCMS: Component;

export default KitVue;
