import type { App } from 'vue';
import type { Component } from 'vue';

declare const KitVue: {
  install(app: App): void;
};

export const components: Record<string, Component>;
export const Accordion: Component;
export const AddAmount: Component;
export const Alert: Component;
export const AlertVarian: Component;
export const Aspect: Component;
export const Breadcrumb: Component;
export const Button: Component;
export const ButtonSize: Component;
export const CardAccount: Component;
export const CardArticle: Component;
export const CardArticleHighlight: Component;
export const CardContent: Component;
export const CardEvent: Component;
export const CardFile: Component;
export const CardProduct: Component;
export const CardProductKonvensional: Component;
export const CardProductSyariah: Component;
export const CardPromo: Component;
export const CardPromoCode: Component;
export const CardVoucher: Component;
export const DatePicker: Component;
export const Dropdown: Component;
export const FilePickerLG: Component;
export const FilePickerSM: Component;
export const InputPersen: Component;
export const Input: Component;
export const InputKtp: Component;
export const InputSmallDate: Component;
export const InputSearch: Component;
export const TextArea: Component;
export const ModalComponent: Component;
export const ListGroupUnordered: Component;
export const ListGroupUnit: Component;
export const ListOrdered: Component;
export const TableData: Component;
export const DataTable: Component;
export const TableSticky: Component;
export const DataApps: Component;
export const Badge: Component;
export const DropdownGroupItem: Component;
export const DropdownItem: Component;
export default KitVue;
